steps:
  - script: |
      . set_pipeline_variables.sh
    displayName: Set Pipeline Variables

  - script: |
      . build.sh
    displayName: 'Build Docker image'
    env:
      VERSION_TAG: $(VERSION_TAG)

  - task: CopyFiles@2
    inputs:
      contents: 'build/**'
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishPipelineArtifact@1
    displayName: 'publish pipeline artifacts'
    inputs:
      targetPath: ' $(Build.ArtifactStagingDirectory)' 
      artifactName:  'artifacts'


pool: "Linux-Docker"
